version: '3.1'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: devbook
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
