GET http://localhost:5000/users

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "Guilherme",
    "email": "teste@teste.com",
    "nickname": "gui123",
    "password": "12345abc"
}
